COPY_OVERRIDES = {
    "zh": {
        "app_subtitle": "本地视频语义检索与片段预览",
        "hero_title": "搜索、网络库、参数设置分区操作",
        "hero_body": "按页面分工操作，减少干扰，定位更快。",
        "search_page_desc": "在独立工作区完成查询、预览与结果分析。",
        "link_page_title": "网络库构建与检索",
        "link_page_desc": "从在线链接构建网络向量库，并直接执行检索。",
        "link_controls_label": "检索输入",
        "link_controls_hint": "输入文本或上传参考图片后，在网络库中检索相似片段。",
        "library_page_desc": "管理本地视频目录、索引状态与向量数据。",
        "settings_page_desc": "统一管理抽帧、检索、预览与运行参数。",
        "network_build_mode": "网络构建模式",
        "network_build": "开始构建",
        "network_import": "导入网络库包",
        "network_export": "导出网络库包",
        "network_links_detail": "查看来源链接",
        "network_open_cache": "打开缓存目录",
        "link_run": "开始检索",
        "clear": "清空输入",
        "network_building": "正在构建网络库...",
        "network_build_done": "构建完成：新增 {new_vectors} 条向量，当前总量 {total_vectors} 条。",
        "network_build_no_new": "（本次未新增向量，可能均为重复或提取失败）",
        "network_build_failed_count": "（失败/无效链接 {count} 条）",
        "network_build_summary": "链接统计：成功 {success}，失败 {failed}，跳过 {skipped}。",
        "network_build_report_path": "构建报告：{path}",
        "network_build_progress_preparing": "准备处理链接（{current}/{total}）...",
        "network_build_progress_resolving": "解析来源中（{current}/{total}）...",
        "network_build_progress_extracting": "抽帧中（{current}/{total}）...",
        "network_build_progress_embedding": "向量生成中（{current}/{total}）...",
        "network_build_progress_merging": "去重与合并中（{current}/{total}）...",
        "network_build_progress_indexed": "已完成第 {current}/{total} 条，新增 {frames} 帧向量。",
        "network_build_progress_skipped": "已跳过第 {current}/{total} 条链接。",
        "network_build_progress_building": "正在写入向量并构建索引...",
        "network_build_progress_completed": "网络库构建完成。",
        "network_precheck_summary": "预检结果：可构建 {accepted}，拦截 {blocked}，风险 {risky}。",
        "network_precheck_all_blocked": "未检测到可构建链接，请使用可访问的视频详情页链接。",
        "network_precheck_dialog_title": "链接预检报告",
        "network_precheck_dialog_subtitle": "可构建 {accepted} | 拦截 {blocked} | 风险 {risky}",
        "network_precheck_dialog_headers": ["#", "状态", "原因", "链接"],
        "network_precheck_status_blocked": "拦截",
        "network_precheck_status_risky": "风险",
        "network_precheck_reason_invalid_url": "链接无效或未识别为视频详情页",
        "network_precheck_reason_unsupported_page": "不支持的页面类型（搜索/列表/频道）",
        "network_precheck_reason_risky_site": "站点可能需要 cookies 或更准确的视频详情页",
        "setting_fps": "抽帧频率",
        "setting_fps_hint": "本地索引与网络构建共用。值越高覆盖越细，但耗时与占用更高。",
        "setting_remote_max_frames": "网库限帧",
        "setting_remote_max_frames_hint": "安全上限。仅在视频很长且 FPS 较高时触发，通常保持默认。",
        "setting_top_k_hint": "每次检索最多返回的结果条数。",
        "setting_search_mode_hint": "按帧检索更细，按片段检索更语义化。",
        "settings_hint": "修改后点击“保存设置”生效。",
        "saved_settings": "设置已保存。",
        "settings_saved_no_rebuild": "设置已保存，后续检索将使用新参数。",
        "settings_saved_chunk_rebuild": "设置已保存。片段相关参数已变更，需重建索引后生效。",
        "settings_saved_full_rebuild": "设置已保存。FPS 已变更，需重建索引（含重新抽帧与向量生成）。",
        "settings_saved_mixed_rebuild": "设置已保存。FPS 与片段参数已变更，需完整重建索引。",
        "library_vectors_title": "本地向量文件详情",
        "network_links_title": "网络来源链接详情",
        "details_title_default": "详情",
        "details_copy_json": "复制 JSON",
        "details_export_json": "导出 JSON",
        "details_empty": "暂无可显示数据。",
        "ready": "就绪",
        "searching": "正在检索...",
        "search_done": "检索完成：耗时 {duration:.2f}s，结果 {count} 条。",
        "link_search_done": "检索完成：耗时 {duration:.2f}s，结果 {count} 条。",
        "no_results": "未找到匹配结果。",
        "search_failed": "检索失败。",
        "link_search_failed": "链接检索失败。",
        "empty_query": "请先输入文本或上传图片。",
        "query_too_short": "输入太短，建议至少描述主体或动作，例如：“夜晚街道上奔跑的男人”。",
        "query_generic_title": "搜索提示",
        "query_generic_hint": "当前描述比较泛，建议补充主体、动作、场景或镜头特征。",
        "query_refined": "已自动整理输入：{query}",
        "link_empty_query": "请先输入视频链接。",
        "warning_title": "提示",
        "error_title": "操作失败",
        "success_title": "操作完成",
        "generic_detail": "详细信息：{detail}",
    },
    "en": {
        "app_subtitle": "Semantic video retrieval with fast clip preview",
        "hero_title": "Operate Search, Remote Library, and Settings independently",
        "hero_body": "Clear page boundaries reduce context switching and mistakes.",
        "search_page_desc": "Run query, preview, and result review in a dedicated workspace.",
        "link_page_title": "Remote Library Build & Search",
        "link_page_desc": "Build a remote vector library from online links and search it directly.",
        "link_controls_label": "Query Input",
        "link_controls_hint": "Enter text or upload a reference image to search similar moments.",
        "library_page_desc": "Manage local folders, index status, and vector assets.",
        "settings_page_desc": "Configure sampling, retrieval, preview, and runtime behavior.",
        "network_build_mode": "Remote Build Mode",
        "network_build": "Build Now",
        "network_import": "Import Remote Pack",
        "network_export": "Export Remote Pack",
        "network_links_detail": "View Source Links",
        "network_open_cache": "Open Cache Folder",
        "link_run": "Search Now",
        "clear": "Clear Input",
        "network_building": "Building remote library...",
        "network_build_done": "Build finished: +{new_vectors} vectors, total {total_vectors}.",
        "network_build_no_new": "(no new vectors; likely duplicates or extraction failures)",
        "network_build_failed_count": "({count} invalid/failed links)",
        "network_build_summary": "Link summary: success {success}, failed {failed}, skipped {skipped}.",
        "network_build_report_path": "Report: {path}",
        "network_build_progress_preparing": "Preparing source ({current}/{total})...",
        "network_build_progress_resolving": "Resolving source ({current}/{total})...",
        "network_build_progress_extracting": "Extracting frames ({current}/{total})...",
        "network_build_progress_embedding": "Generating embeddings ({current}/{total})...",
        "network_build_progress_merging": "Deduplicating and merging ({current}/{total})...",
        "network_build_progress_indexed": "Completed source {current}/{total}, indexed {frames} frames.",
        "network_build_progress_skipped": "Skipped source {current}/{total}.",
        "network_build_progress_building": "Writing vectors and building index...",
        "network_build_progress_completed": "Remote library build completed.",
        "network_precheck_summary": "Precheck: accepted {accepted}, blocked {blocked}, risky {risky}.",
        "network_precheck_all_blocked": "No buildable links detected. Please provide direct, accessible video detail-page URLs.",
        "network_precheck_dialog_title": "Link Precheck Report",
        "network_precheck_dialog_subtitle": "Accepted {accepted} | Blocked {blocked} | Risky {risky}",
        "network_precheck_dialog_headers": ["#", "Status", "Reason", "Link"],
        "network_precheck_status_blocked": "Blocked",
        "network_precheck_status_risky": "Risky",
        "network_precheck_reason_invalid_url": "Invalid link or not recognized as a video detail page",
        "network_precheck_reason_unsupported_page": "Unsupported page type (search/list/channel)",
        "network_precheck_reason_risky_site": "Site may require cookies or a more direct detail-page URL",
        "setting_fps": "Sample FPS",
        "setting_fps_hint": "This is the base sampling density. The app automatically samples short videos more densely and long videos more sparsely.",
        "setting_sampling_fps_mode": "Sampling Mode",
        "setting_sampling_fps_mode_hint": "Fixed mode always uses the unified FPS. Dynamic mode matches the FPS rule for the current video duration.",
        "setting_sampling_fps_mode_fixed": "Fixed",
        "setting_sampling_fps_mode_dynamic": "Dynamic",
        "setting_sampling_fps_rules_placeholder": "Example: 0-10m=2; 10m-30m=1; 30m-=0.4",
        "setting_sampling_fps_rules_edit": "Edit Rules",
        "setting_sampling_fps_rules_hint": "Use 'start-end=FPS' rules with minute units only (m), for example 10m or 60m. Leave the end empty for no upper bound.",
        "setting_sampling_fps_rules_invalid": "Invalid dynamic sampling rules. Use 'start-end=FPS', for example: 0-10m=2; 10m-30m=1; 30m-=0.4",
        "sampling_rules_title": "Edit Sampling Rules",
        "sampling_rules_hint": "Fill one duration range and FPS per row. Minute units only (m), such as 10m or 60m. Leave the end empty for no upper bound.",
        "sampling_rules_col_start": "Start",
        "sampling_rules_col_end": "End",
        "sampling_rules_col_fps": "FPS",
        "sampling_rules_add": "Add Row",
        "sampling_rules_remove": "Remove Selected",
        "sampling_rules_apply": "Apply Rules",
        "sampling_rules_empty": "Leave empty to use the base FPS for all videos.",
        "sampling_rules_invalid_row": "Rule row {row} is invalid. Check the duration and FPS format.",
        "setting_dynamic_fps_reference_duration": "Reference Duration",
        "setting_dynamic_fps_reference_duration_hint": "When video duration matches this value, dynamic mode uses the unified FPS above. Shorter videos sample more densely and longer videos sample more sparsely.",
        "setting_dynamic_fps_min": "Dynamic Min FPS",
        "setting_dynamic_fps_min_hint": "Lower bound for dynamic sampling.",
        "setting_dynamic_fps_max": "Dynamic Max FPS",
        "setting_dynamic_fps_max_hint": "Upper bound for dynamic sampling.",
        "setting_remote_max_frames": "Remote Frame Cap (Advanced)",
        "setting_remote_max_frames_hint": "Safety cap only. Usually keep default unless you process very long videos.",
        "setting_top_k_hint": "Maximum number of results returned per query.",
        "setting_search_mode_hint": "Frame mode is finer; Chunk mode is more semantic.",
        "settings_hint": "Click Save Settings to apply changes.",
        "saved_settings": "Settings saved.",
        "settings_saved_no_rebuild": "Settings saved. New values will apply to future searches.",
        "settings_saved_chunk_rebuild": "Settings saved. Chunk-related changes require index rebuild.",
        "settings_saved_full_rebuild": "Settings saved. FPS changed, full index rebuild required.",
        "settings_saved_mixed_rebuild": "Settings saved. FPS and Chunk settings changed, full rebuild required.",
        "library_vectors_title": "Local Vector File Details",
        "network_links_title": "Remote Source Link Details",
        "details_title_default": "Details",
        "details_copy_json": "Copy JSON",
        "details_export_json": "Export JSON",
        "details_empty": "No source available.",
        "ready": "Ready",
        "searching": "Searching...",
        "search_done": "Search completed in {duration:.2f}s, {count} results.",
        "link_search_done": "Search completed in {duration:.2f}s, {count} results.",
        "no_results": "No matches found.",
        "search_failed": "Search failed.",
        "link_search_failed": "Link search failed.",
        "empty_query": "Enter text or upload an image first.",
        "query_too_short": "The query is too short. Describe at least the subject or action.",
        "query_generic_title": "Search Tip",
        "query_generic_hint": "This description is broad. Add subject, action, scene, or shot details.",
        "query_refined": "Normalized query: {query}",
        "link_empty_query": "Enter a video link first.",
        "warning_title": "Notice",
        "error_title": "Operation Failed",
        "success_title": "Done",
        "generic_detail": "Details: {detail}",
    },
}


def apply_copy_overrides(base_texts, language):
    merged = dict(base_texts or {})
    merged.update(COPY_OVERRIDES.get(language, {}))
    return merged
